name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-2019

    steps:
    - uses: msys2/setup-msys2@v2 
      with:
        update: true
        install: >-
          git
          python
          make
          gcc

    - name: Setup
      run: pip3 install gitman

    - shell: powershell
      run: |
        echo "[msys2 make version]"
        msys2 -c 'make --version'
        echo "[msys2 GCC version]"
        msys2 -c 'gcc --version'
        echo "[windows CMake version]"
        cmake --version

